version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_CONNECTION_STRING=mongodb://admin:123@mongodb:27017
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123