version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: cppmongo:1.0.1
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_CONNECTION_STRING=mongodb://admin:123@mongodb:27017
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:5.0.25
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123

# docker-compose exec -it mongodb mongosh --username admin --password 123
